apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-service-account-provisioning
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  service-accounts.yaml: |
    apiVersion: 1
    serviceAccounts:
      - orgId: 1
        name: k8s-sidecar
        role: Admin
        isDisabled: false
        tokens:
          - name: k8s-sidecar-token
            key: ${GF_SIDECAR_TOKEN}
